sudo: required

language: python3
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
services:
  - docker
before_install:
  - docker build -t kanelbulle .
script:
  - docker run kanelbulle
