version: '3'
services:
  bot:
    depends_on:
      - db
    build:
      context: ./bot
      dockerfile: Dockerfile
  db:
    image: postgres:latest
    volumes:
      - ./.data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kanelbulle
      POSTGRES_DB: kanelbulledb
